app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('public.village.show');
});

Route::get('/', 'VillageController@index');

Route::get('/village/import', 'VillageController@import');
Route::post('/village/import', 'VillageController@importshow');

Route::post('/village/upload', 'VillageController@upload');
Route::post('/location/upload/{id}', 'LocationController@upload');
Route::post('/person/upload/{id}', 'PersonController@upload');
Route::get('/village/deteleimage/{vid}/{id}', 'VillageController@destroyImge');
Route::get('/person/deteleimage/{pid}/{id}', 'PersonController@destroyImge');
Route::get('/location/deteleimage/{lid}/{id}', 'LocationController@destroyImge');

Route::get('/dashboard', function () {
    return view('dashboard.home');
});
Route::get('/provinces', 'DataController@provinces');
Route::get('/districts', 'DataController@districts');
Route::get('/agas', 'DataController@agas');
Route::get('/postal', 'DataController@postals');

Route::get('/getlist', 'VillageController@getlist');

Route::get('/language/{locale}', function ($locale) {
	Session::set('applocale', $locale);
	App::setLocale($locale);
	return Redirect::back();
});



Route::resource('/village','VillageController');
Route::resource('/location','LocationController');
Route::resource('/person','PersonController');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::get('auth/facebook', 'Auth\AuthController@redirectToProvider');
Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallback');

//Route::get('excel', 'ExcelController@excel');

app/Models/Person.php
<?php

namespace App\Models;

use Moloquent;

class Person extends Moloquent
{
    //
    protected $connection = 'mongodb';
    protected $collection = 'person';
    protected $primaryKey = "_id";
    protected $fillable = [
    	'name','description','village_id'
    ];

    public function village()
    {
        return $this->belongsTo('App\Models\Village', 'village_id');
    }
    public function images()
    {
        return $this->embedsMany('App\Models\Personimage');
    }

   

}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Person;
use App;
//use Request;
use Input;
use Image;

class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $people = Person::all();  
        return view('dashboard/person/index', ['people'=>$people]);        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $village_id = $request->input('village_id'); 
        $data = ['village_id'=>$village_id];
        return view('dashboard/person/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
        $loc = Person::create($input);
        if(Input::file()){
            $this->upload($loc->_id, $request);
        }
        
        return redirect('village/'.$input['village_id']);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $person = Person::findOrFail($id);  

        //return $village;
        return view('dashboard/person/show',['person'=>$person, 'images'=>$person->images()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $person = Person::findOrFail($id);
        return view('dashboard/person/edit',['person'=>$person]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $person = Person::findOrFail($id); 
        $person->update($request->all()) ;
       return redirect('person/'.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $person = Person::findOrFail($id);
        $img = $person->images()->all();
        foreach ($img as $i) {
            unlink(public_path('img/person/'.$i->name));
        }
        $person->delete(); 
        //$village = App\Models\Village::find($location->village_id);
        return redirect('village/'.$person->village_id);
    }

    public function destroyImge($pid, $id)
    {
        $person = Person::findOrFail($pid);
        $img = $person->images()->find($id);
        unlink(public_path('img/person/'.$img->name));
        $img->delete();
        //$village->images()->delete($id);
        //unlink(public_path('img/village/'.$img->name));
        return redirect('person/'.$pid);
    }

    public function upload($id, Request $request){

        $image = Input::file('file');
        $filename  = time() . '.' . $image->getClientOriginalExtension();
        $filename  = time() . '.' . $id.'.jpg';
        $path = public_path('img/person/'.$filename);
        Image::make($image->getRealPath())->resize(600, null, function ($constraint) {
            $constraint->aspectRatio();
        })->save($path);
        $person = Person::findOrFail($id);
        $image = $person->images()->create(array('name' => $filename));
        return redirect('person/'.$id);
        
    }


}

resources/views/dashboard/person/create.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6">    
        {!! Form::open(['url'=>'person' ,'files' => true]) !!}
        <h3>{{ trans('village.title_special_people') }}</h3> 
        <div class="form-group">
            <input type="hidden" class="form-control" id="name" name="village_id" value="{{ $village_id }}">
            <label for="name">{{ trans('village.personname') }}</label> 
            {!! Form::text('name', null, ['class'=>'form-control']) !!}            
        </div>       
        <div class="form-group">
            <label for="description">{{ trans('village.description') }}</label>
            {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
        </div>
        <div class="form-group">                     
            {!! Form::file('file') !!}            
        </div>  
        <button type="submit" class="btn btn-primary">Submit</button>
        {!! Form::close() !!}    
    <br>
    <br>
    <br>
</div>
@stop

resources/views/dashboard/person/edit.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6">    
        {!! Form::model($person, ['method'=>'PATCH', 'url'=>'person/'.$person->_id]) !!}
        <h3>{{ trans('village.title_special_people') }}</h3> 
        <div class="form-group">
            <input type="hidden" class="form-control" id="name" name="person_id" value="{{ $person }}">
            <label for="name">{{ trans('village.personname') }}</label> 
            {!! Form::text('name', null, ['class'=>'form-control']) !!}            
        </div>       
        <div class="form-group">
            <label for="description">{{ trans('village.description') }}</label>
            {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
        </div>         
        <button type="submit" class="btn btn-primary">Submit</button>
        {!! Form::close() !!}    
    <br>
    <br>
    <br>
</div>
@stop

resources/views/dashboard/person/index.blade.php
@extends('public/master')

@section('content')
<div class="col-md-12">
	<h1>People</h1><!-- <a href="location/create"><span class="glyphicon glyphicon-plus"></span> Add new</a> -->
    <ul class="item_wrapper row">
    	 @foreach ($people as $person)                         
	    <li class="col-md-2"><a href="/person/{{ $person->_id }}">{{translate($person, 'name')}}</a></li>
		@endforeach        	
    </ul>
</div>
@stop

resources/views/dashboard/person/show.blade.php
@extends('public/master')
@section('content')
<div class="col-md-6"> 
	<a href="/village/{{$person->village->id}}"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> {{translate($person->village, 'name')}}</a> 
	<h1>{{translate($person, 'name')}} <a href="/person/{{ $person->id }}/edit"><span class="badge">edit</span></a></h1>   
	<p>{{translate($person, 'description')}}</p>
</div>
<div class="col-md-6"> 
	<h3>Images</h3>	
	<div class="image_wrapper">

	@foreach ($person->images as $image)  
	<div class="imgthumb">                     
	    	<a class="delimg" href="/person/deteleimage/{{{$person->id}}}/{{$image->id}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>                       
	    <img src="{{ URL::asset('img/person/'.$image->name) }}" alt="">
	</div>
	@endforeach
	<div class="clear"></div>
	</div> 
	{!! Form::open(['url'=>'person/upload/'.$person->_id ,'files' => true]) !!}       
        <div class="form-group">   
        	<input type="hidden" class="form-control" id="name" name="person_id" value="{{ $person->id }}">         
            {!! Form::file('file') !!}            
        </div>        
        <button type="submit" class="btn btn-primary">Upload</button>
    {!! Form::close() !!}
</div>
<div class="col-md-12">
<hr>
<form action="{{ URL::route('person.destroy',$person->id) }}" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <button>Delete Person</button>
</form>
</div>
@stop