app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('public.village.show');
});

Route::get('/', 'VillageController@index');

Route::get('/village/import', 'VillageController@import');
Route::post('/village/import', 'VillageController@importshow');

Route::post('/village/upload', 'VillageController@upload');
Route::post('/location/upload/{id}', 'LocationController@upload');
Route::post('/person/upload/{id}', 'PersonController@upload');
Route::get('/village/deteleimage/{vid}/{id}', 'VillageController@destroyImge');
Route::get('/person/deteleimage/{pid}/{id}', 'PersonController@destroyImge');
Route::get('/location/deteleimage/{lid}/{id}', 'LocationController@destroyImge');

Route::get('/dashboard', function () {
    return view('dashboard.home');
});
Route::get('/provinces', 'DataController@provinces');
Route::get('/districts', 'DataController@districts');
Route::get('/agas', 'DataController@agas');
Route::get('/postal', 'DataController@postals');

Route::get('/getlist', 'VillageController@getlist');

Route::get('/language/{locale}', function ($locale) {
	Session::set('applocale', $locale);
	App::setLocale($locale);
	return Redirect::back();
});



Route::resource('/village','VillageController');
Route::resource('/location','LocationController');
Route::resource('/person','PersonController');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::get('auth/facebook', 'Auth\AuthController@redirectToProvider');
Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallback');

//Route::get('excel', 'ExcelController@excel');

app/Models/Village.php
<?php

namespace App\Models;

use Moloquent;

class Village extends Moloquent
{
    //
    protected $connection = 'mongodb';
    protected $collection = 'village';
    protected $primaryKey = "_id";
    protected $fillable = [
    	'name', 'village_num','province_id', 'district_id', 'agadiv_id','othernames','description', 'postoffice', 'nearest_town',
        'climate','geo_variations','geo_type', 'forest_type','forest_desc', 'plants',
        'societies','groups','organisations','business', 'latlng','translate'
    ];

    public function images()
    {
        return $this->embedsMany('App\Models\Villageimage');
    }
    public function locations()
    {
        return $this->hasMany('App\Models\Location', 'village_id');
    }
    public function people()
    {
        return $this->hasMany('App\Models\Person', 'village_id');
    }
   
    public function province()
    {
        return $this->belongsTo('App\Models\Province', 'province_id');
    }
    public function district()
    {
        return $this->belongsTo('App\Models\District', 'district_id');
    }
    public function agadiv()
    {
        return $this->belongsTo('App\Models\Agadiv', 'agadiv_id');
    }
    public function postal()
    {
        return $this->belongsTo('App\Models\Postal', 'postoffice');
    }
}

app/Http/Controllers/VillageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Village;
use App\Models\Province;
use App\Models\Agadiv;
use App\Models\District;
use App;
//use Request;
use Input;
use Image;
use Excel;

class VillageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
        //$provinces = Province::pluck('name', '_id'); 
        $provinces = Province::all()->pluck('name', '_id'); 
        //return $provinces; 
        
        $villages = '';
        if(Input::has('agadiv_id') && Input::get('agadiv_id') != 'Please select'){
            $agadiv = Agadiv::findOrFail(Input::get('agadiv_id')); 
            $villages = $agadiv->villages;
        }else if(Input::has('district_id') && Input::get('district_id') != 'Please select'){
            $district = District::findOrFail(Input::get('district_id')); 
            $villages = $district->villages;  
            
        }else if (Input::has('province_id') && Input::get('province_id') != 'Please select')
        {
            $Province = Province::findOrFail(Input::get('province_id'));  
            $villages = $Province->villages;  
        } else{
            $villages = Village::all();  
        }

        return view('dashboard/village/index', ['villages'=>$villages,'provinces'=>$provinces]);
        // return view('master',['villages'=>$villages]);
        
    }

    public function getlist(Request $request){
        $type = $request->input('type');
        $id = $request->input('id');
        switch ($type) {
            case 'district':
                $list = Province::find($id)->districts->lists('name', '_id'); 
                break;
            case 'agadiv':
                $list = District::find($id)->agadivs->lists('name', '_id'); 
                break;
            case 'gndiv':
                $list = Agadiv::find($id)->gndivs->lists('name', '_id'); 
                break;
             case 'postoffice':
                $list = District::find($id)->postoffices->lists('name', '_id'); 
                break;
            default:
                # code...
                break;
        }        
        return $list;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $provinces = Province::all()->pluck('name', '_id'); 
        $data = ['provinces'=>$provinces];
        return view('dashboard/village/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
        Village::create($input);
        return redirect('village');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $village = Village::findOrFail($id);  
        $locations = $village->locations;
        $people = $village->people;
        //print_r($locations);
        //dd($village);
        return view('dashboard/village/show',['village'=>$village, 'images'=>$village->images(), 'locations'=>$locations, 'people'=>$people]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $village = Village::findOrFail($id); 
        $provinces = Province::lists('name', '_id');
        $districts = Province::find($village->province_id)->districts->lists('name', '_id'); 
        $agadivs = District::find($village->district_id)->agadivs->lists('name', '_id');
        $postoffices = District::find($village->district_id)->postoffices->lists('name', '_id');
        if($request->input('group') == 2){
            return view('dashboard/village/edit2',['village'=>$village, 'provinces'=>$provinces, 'districts'=>$districts, 'agadivs'=>$agadivs, 'postoffices'=>$postoffices]);
        }else if($request->input('group') == 3){
            return view('dashboard/village/edit3',['village'=>$village, 'provinces'=>$provinces, 'districts'=>$districts, 'agadivs'=>$agadivs, 'postoffices'=>$postoffices]);
        }
        return view('dashboard/village/edit',['village'=>$village, 'provinces'=>$provinces, 'districts'=>$districts, 'agadivs'=>$agadivs, 'postoffices'=>$postoffices]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $village = Village::findOrFail($id); 
        $village->update($request->all()) ;
       return redirect('village/'.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $village = Village::findOrFail($id);
        $village->locations()->delete();
        $village->people()->delete();
        $img = $village->images()->all();
        foreach ($img as $i) {
            unlink(public_path('img/village/'.$i->name));
        }
        $village->delete(); 
        //$village = App\Models\Village::find($location->village_id);
        return redirect('village/'.$village->village_id);
    }
    public function destroyImge($vid, $id)
    {
        $village = Village::findOrFail($vid);
        $img = $village->images()->find($id);
        unlink(public_path('img/village/'.$img->name));
        $img->delete();
        //$village->images()->delete($id);
        //unlink(public_path('img/village/'.$img->name));
        return redirect('village/'.$vid);
    }
    public function upload(Request $request){

        $image = Input::file('file');
        $filename  = time() . '.' . $image->getClientOriginalExtension();

        $village_id = $request->input('village_id');        
        
        
        $village = Village::findOrFail($village_id);

        $filename  = time() . '.' . $village->_id.'.jpg';
        $path = public_path('img/village/'.$filename);

        
        Image::make($image->getRealPath())->resize(600, null, function ($constraint) {
            $constraint->aspectRatio();
        })->save($path);

        $image = $village->images()->create(array('name' => $filename));
        return redirect('village/'.$village_id);
    }


    public function import()
    {
        $provinces = Province::lists('name', '_id'); 
        $data = ['provinces'=>$provinces];
        return view('dashboard/village/import', $data);
    }
    public function importshow()
    {
        //return view('dashboard/village/importshow', $data);
        if (Input::file('file')->isValid()) {
            $destinationPath = 'uploads'; // upload path
            $extension = Input::file('file')->getClientOriginalExtension(); // getting image extension
            $fileName = rand(11111,99999).'.'.$extension; // renameing image
            Input::file('file')->move($destinationPath, $fileName); // uploading file to given path
          
            $results = Excel::selectSheets('Sheet1')->load('uploads/'.$fileName, function($reader) {
               /*
                // Getting all results
                $results = $reader->get()->toArray();
                //$data = ['results'=>$results];
                
                 foreach($results as $row)
                {
                    echo $row['english'].' - '.$row['sinhala'].'<br>';
                }*/
                
                

            })->get();
            $rows = array();
            foreach ($results as $row) {
                $input = ['name'=>$row['english'], 
                        'village_num'=>$row['number'],
                        'province_id'=> Input::get('province_id'), 
                        'district_id'=> Input::get('district_id'), 
                        'agadiv_id'=> Input::get('agadiv_id'),
                        'translate'=> ['si'=>['name'=>$row['sinhala']]]
                        ];
                        $rows[] = $input;
                Village::create($input);
            }
            unlink(public_path('uploads/'.$fileName));
            $data = ['results'=>$rows];
            return view('dashboard/village/importshow', $data);

        }
        
        
    }


}

resources/views/dashboard/village/create.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6"> 
    
        {!! Form::open(['url'=>'village']) !!}
        <h3>{{ trans('village.title_location_info') }}</h3>        
        <div class="form-group">
            <label for="province">{{ trans('village.province') }}</label>
            {!! Form::select('province_id', [null=>'Please select'] + $provinces->toArray(), null, ['class'=>'form-control', 'id'=>'province']) !!}            
        </div>
        <div class="form-group">
            <label for="district">{{ trans('village.district') }}</label>
            {!! Form::select('district_id', array(), null, ['class'=>'form-control', 'id'=>'district']) !!}
            
        </div>
        <div class="form-group">
            <label for="aga_div">{{ trans('village.aga_div') }}</label>
            {!! Form::select('agadiv_id', array(), null, ['class'=>'form-control', 'id'=>'agadiv']) !!}
        </div>
        <div class="form-group">
            <label for="village_num">{{ trans('village.name') }}</label>            
            <input type="text" class="form-control" id="gndiv" name="name">
        </div>
        <div class="form-group">
            <label for="other_names">{{ trans('village.other_names') }}</label>
            <input type="text" class="form-control" id="name" name="othernames">
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.postoffice') }}</label>
            {!! Form::select('postoffice', array(), null, ['class'=>'form-control', 'id'=>'postoffice']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.nearest_town') }}</label>
            <input type="text" class="form-control" id="name" name="nearest_town">
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.description') }}</label>
           <textarea type="text" class="form-control" id="name" name="description"/></textarea>            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.latlng') }}</label>
            <input type="text" class="form-control latlng" id="latlng" name="latlng" readonly="readonly">            
        </div>
        <hr>        
        <button type="submit" class="btn btn-primary">Submit</button>
        {!! Form::close() !!}    
    <br>
    <br>
    <br>
</div>
@stop

@section('script')
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=true"></script>
<script>
$(document).ready(function(){
    $('.latlng').on('click', function(e){
        $('.lightbox').show();
        $('.light-content').show();
        var province = $("#province option:selected").text();        
        var district = $("#district option:selected").text();
        var agadiv = $("#agadiv option:selected").text();;
        
        if (province === 'Please select') {
             province = '';
        };
        if (district === 'Please select') {
             district = '';
        };
        if (agadiv === 'Please select') {
             agadiv = '';
        };
        var txt ='';
       
        
        if (agadiv != '') {
            txt += agadiv+', '
        };
        if (district != '' ) {
            txt += district+' District, '
        };
         if (province != '') {
            txt += province+' Province, '
        };
        txt += 'Sri Lanka'
        console.log(txt );
        initMap(txt);
    });   
    $('.lightbox').on('click', function(e){
        $('.lightbox').hide();
        $('.light-content').hide();
        
    });


    function initMap(txt) {
      // Create a map object and specify the DOM element for display.
        var map;
        var markers = [];
        var latlng = $('#latlng').val();
        if (latlng !='') {
                latlng = latlng.split(',');
        }
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({
        'address': txt
        }, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
           
            if ($('#latlng').val() !='') {                
                var myOptions = {
                zoom: 10,
                center: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])},
                mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }else{
                var myOptions = {
                    zoom: 10,
                    center: results[0].geometry.location,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }
                
            map = new google.maps.Map(document.getElementById("map"), myOptions);
            
            var marker = new google.maps.Marker({
                position: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])}, 
                map: map
            });
            markers.push(marker);

            google.maps.event.addListener(map, "click", function(e) {  

                placeMarker(e.latLng);
                $('#latlng').val(e.latLng.lat()+','+e.latLng.lng());
                //console.log("Latitude: " + e.latLng.lat() + " Longitude: " + e.latLng.lng());
            });
            /*var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });*/
        }
        });
        
        function placeMarker(location) {
            clearMarkers();
            var marker = new google.maps.Marker({
                position: location, 
                map: map
            });
            markers.push(marker);
        }
        function clearMarkers() {
          for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
          }
        }

    }
});
</script>  
  
@stop

resources/views/dashboard/village/edit.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6">    
        {!! Form::model($village, ['method'=>'PATCH', 'url'=>'village/'.$village->_id]) !!}
        <h3>{{ trans('village.title_location_info') }}</h3>        
        <div class="form-group">
            <label for="province">{{ trans('village.province') }}</label>
            {!! Form::select('province_id', [null=>'Please Select'] + $provinces->toArray(), $village->province_id, ['class'=>'form-control', 'id'=>'province']) !!}            
        </div>
        <div class="form-group">
            <label for="district">{{ trans('village.district') }}</label>
            {!! Form::select('district_id', $districts, $village->district_id, ['class'=>'form-control', 'id'=>'district']) !!}
            
        </div>
        <div class="form-group">
            <label for="aga_div">{{ trans('village.aga_div') }}</label>
            {!! Form::select('agadiv_id', $agadivs, $village->agadiv_id, ['class'=>'form-control', 'id'=>'agadiv']) !!}
        </div>
        <div class="form-group">
            <label for="village_num">{{ trans('village.name') }}</label> 
            {!! Form::text('name', null, ['class'=>'form-control', 'id'=>'gndiv']) !!}                       
            
        </div>
        <div class="form-group">
            <label for="other_names">{{ trans('village.other_names') }}</label>
            {!! Form::text('othernames', null, ['class'=>'form-control', 'id'=>'othernames']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.postoffice') }}</label>
            {!! Form::select('postoffice', $postoffices, $village->postoffice, ['class'=>'form-control', 'id'=>'postoffice']) !!}
            <!-- {!! Form::text('postoffice', null, ['class'=>'form-control', 'id'=>'postoffice']) !!} -->
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.nearest_town') }}</label>
            {!! Form::text('nearest_town', null, ['class'=>'form-control', 'id'=>'nearest_town']) !!}
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.description') }}</label>
            {!! Form::textarea('description', null, ['class'=>'form-control', 'id'=>'agadiv']) !!}              
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.latlng') }}</label>
            {!! Form::text('latlng', null, ['readonly'=>'readonly' ,'class'=>'form-control latlng', 'id'=>'latlng']) !!} 
            
        </div>
       
        <button type="submit" class="btn btn-primary">Save</button> <a href="/village/{{ $village->id }}">Cancel</a>
        {!! Form::close() !!}    

</div>
@stop

@section('script')
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=true"></script>
<script>
$(document).ready(function(){
    $('.latlng').on('click', function(e){
        $('.lightbox').show();
        $('.light-content').show();
        var province = $("#province option:selected").text();        
        var district = $("#district option:selected").text();
        var agadiv = $("#agadiv option:selected").text();;
        
        if (province === 'Please select') {
             province = '';
        };
        if (district === 'Please select') {
             district = '';
        };
        if (agadiv === 'Please select') {
             agadiv = '';
        };
        var txt ='';
       
        
        if (agadiv != '') {
            txt += agadiv+', '
        };
        if (district != '' ) {
            txt += district+' District, '
        };
         if (province != '') {
            txt += province+' Province, '
        };
        txt += 'Sri Lanka'
        console.log(txt );
        initMap(txt);
    });   
    $('.lightbox').on('click', function(e){
        $('.lightbox').hide();
        $('.light-content').hide();
        
    });


    function initMap(txt) {
      // Create a map object and specify the DOM element for display.
        var map;
        var markers = [];
        var latlng = $('#latlng').val();
        if (latlng !='') {
                latlng = latlng.split(',');
        }
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({
        'address': txt
        }, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
           
            if ($('#latlng').val() !='') {                
                var myOptions = {
                zoom: 10,
                center: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])},
                mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }else{
                var myOptions = {
                    zoom: 10,
                    center: results[0].geometry.location,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }
                
            map = new google.maps.Map(document.getElementById("map"), myOptions);
            
            var marker = new google.maps.Marker({
                position: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])}, 
                map: map
            });
            markers.push(marker);

            google.maps.event.addListener(map, "click", function(e) {  

                placeMarker(e.latLng);
                $('#latlng').val(e.latLng.lat()+','+e.latLng.lng());
                //console.log("Latitude: " + e.latLng.lat() + " Longitude: " + e.latLng.lng());
            });
            /*var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });*/
        }
        });
        
        function placeMarker(location) {
            clearMarkers();
            var marker = new google.maps.Marker({
                position: location, 
                map: map
            });
            markers.push(marker);
        }
        function clearMarkers() {
          for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
          }
        }

    }
});
</script>  
  
@stop

resources/views/dashboard/village/edit2.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6">    
        {!! Form::model($village, ['method'=>'PATCH', 'url'=>'village/'.$village->_id]) !!}
        <h3>{{ trans('village.title_natural_geo_info') }}</h3>        
        <div class="form-group">
            <label for="name">{{ trans('village.climate') }}</label>
            {!! Form::text('climate', null, ['class'=>'form-control', 'id'=>'climate']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.geo_variations') }}</label>
            {!! Form::text('geo_variations', null, ['class'=>'form-control', 'id'=>'geo_variations']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.geo_type') }}</label>
            {!! Form::text('geo_type', null, ['class'=>'form-control', 'id'=>'geo_type']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.forest_type') }}</label>
            {!! Form::text('forest_type', null, ['class'=>'form-control', 'id'=>'forest_type']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.forest_desc') }}</label>
            {!! Form::text('forest_desc', null, ['class'=>'form-control', 'id'=>'forest_desc']) !!}            
        </div>
        <div class="form-group">
            <label for="name">{{ trans('village.plants') }}</label>
            {!! Form::text('plants', null, ['class'=>'form-control', 'id'=>'plants']) !!}            
        </div>
        <button type="submit" class="btn btn-primary">Save</button> <a href="/village/{{ $village->id }}">Cancel</a>
        {!! Form::close() !!}    

</div>
@stop

resources/views/dashboard/village/show.blade.php
@extends('public/master')
@section('content')
<div class="col-md-6"> 
	<h1>{{translate($village, 'name')}} <a href="/village/{{ $village->id }}/edit"><span class="badge">edit</span></a></h1>   
	<p>{{translate($village, 'description')}}</p>
	<h3>{{ trans('village.title_location_info') }}</h3>	
	<p>{{translate($village->province, 'name')}} province, {{translate($village->district, 'name')}} District, {{translate($village->agadiv, 'name')}} AGA Division</p>		
	<p><strong>{{ trans('village.postoffice') }} : </strong>{{translate($village->postal, 'name')}} - {{translate($village->postal, 'postal_code')}}</p>			        
	<p><strong>{{ trans('village.nearest_town') }} : </strong>{{translate($village, 'nearest_town')}}</p>	
	<hr>
	<h3>{{ trans('village.title_natural_geo_info') }} <a href="/village/{{ $village->id }}/edit?group=2"><span class="badge">edit</span></a></h3>			
	<p><strong>{{ trans('village.climate') }}: </strong>{{translate($village, 'climate')}}</p>
	<p><strong>{{ trans('village.geo_variations') }} : </strong>{{translate($village, 'geo_variations')}}</p>			        
	<p><strong>{{ trans('village.geo_type') }} : </strong>{{translate($village, 'geo_type')}}</p>			        
	<p><strong>{{ trans('village.forest_type') }} : </strong>{{translate($village, 'forest_type')}}</p>			        
	<p><strong>{{ trans('village.forest_desc') }} : </strong>{{translate($village, 'forest_desc')}}</p>			        
	<p><strong>{{ trans('village.plants') }} : </strong>{{translate($village, 'plants')}}</p>
	<hr>
	<h3>{{ trans('village.title_orgs_ins') }}  <a href="/village/{{ $village->id }}/edit?group=3"><span class="badge">edit</span></a></h3>			
	<p><strong>{{ trans('village.societies') }} : </strong>{{translate($village, 'societies')}}</p>
	<p><strong>{{ trans('village.groups') }} : </strong>{{translate($village, 'groups')}}</p>			        
	<p><strong>{{ trans('village.organisations') }} : </strong>{{translate($village, 'organisations')}}</p>			        
	<p><strong>{{ trans('village.business') }}: </strong>{{translate($village, 'business')}}</p>			        
	

</div>
<div class="col-md-6">
	<div class="row">
		<div class="col-md-12 mapouter"> 
			<div class="map mapbox" id="mapbox" ></div>			
		</div>
		<div class="col-md-12"> 
			<h3>Images</h3>	
			<div class="image_wrapper">

			@foreach ($village->images as $image)
				<div class="imgthumb">                     
			    	<a class="delimg" href="/village/deteleimage/{{{$village->id}}}/{{$image->id}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
			    	<img src="{{ URL::asset('img/village/'.$image->name) }}" alt="">
			    </div>    
			@endforeach
				<div class="clear"></div>
			</div> 
			{!! Form::open(['url'=>'village/upload' ,'files' => true]) !!}       
		        <div class="form-group">   
		        	<input type="hidden" class="form-control" id="name" name="village_id" value="{{ $village->id }}">         
		            {!! Form::file('file') !!}            
		        </div>        
		        <button type="submit" class="btn btn-primary">Upload</button>
		    {!! Form::close() !!}
		</div>
	</div>
</div>

<div class="col-md-12">
<hr>
	<h3>{{ trans('village.title_special_loc') }}</h3>
	<a href="/location/create?village_id={{$village->id}}"><span class="glyphicon glyphicon-plus"></span> Add  Special location</a><br>
	<div class="image_wrapper row">
		@foreach ($locations as $image)
			<div class="col-md-6  imgthumb">				
				<a href="/location/{{$image->id}}">
					<div>
						@if (isset($image->images[0])) 	   
						<img src="{{ URL::asset('img/location/'.$image->images[0]->name) }}" alt="">
						@endif
					</div>
					<span>{{$image->name}}</span>
				</a> 
			</div>			
		@endforeach
		<div class="clear"></div>
	</div>


	<hr>
	<h3>{{ trans('village.title_special_people') }}</h3>
	<a href="/person/create?village_id={{$village->id}}"><span class="glyphicon glyphicon-plus"></span> Add  a person</a><br>
	<div class="image_wrapper row">
		@foreach ($people as $image)
			<div class="col-md-6 imgthumb">				
				<a href="/person/{{$image->id}}">
					<div>
						@if (isset($image->images[0])) 	   
						<img src="{{ URL::asset('img/person/'.$image->images[0]->name) }}" alt="">
						@endif
					</div>
					<span>{{$image->name}}</span>
				</a> 
			</div>			
		@endforeach
		<div class="clear"></div>
	</div>
<hr>
<form action="{{ URL::route('village.destroy',$village->id) }}" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <button>Delete Village</button>
</form>	
	
</div>

@stop

@section('script')
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=true"></script>
<script>
$(document).ready(function(){
    
	initMap();

    function initMap() {
      // Create a map object and specify the DOM element for display.
        var map;
        
        var latlng ="{{ $village->latlng }}";
        if (latlng !='') {
                latlng = latlng.split(',');
        }
             
        var myOptions = {
        	zoom: 14,
	        center: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])},
	        mapTypeId: google.maps.MapTypeId.ROADMAP
	        }
                
        	map = new google.maps.Map(document.getElementById("mapbox"), myOptions);
        
	        var marker = new google.maps.Marker({
	            position: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])}, 
	            map: map
	        });
            
        }
        });
        

</script>  
  
@stop