app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('public.village.show');
});

Route::get('/', 'VillageController@index');

Route::get('/village/import', 'VillageController@import');
Route::post('/village/import', 'VillageController@importshow');

Route::post('/village/upload', 'VillageController@upload');
Route::post('/location/upload/{id}', 'LocationController@upload');
Route::post('/person/upload/{id}', 'PersonController@upload');
Route::get('/village/deteleimage/{vid}/{id}', 'VillageController@destroyImge');
Route::get('/person/deteleimage/{pid}/{id}', 'PersonController@destroyImge');
Route::get('/location/deteleimage/{lid}/{id}', 'LocationController@destroyImge');

Route::get('/dashboard', function () {
    return view('dashboard.home');
});
Route::get('/provinces', 'DataController@provinces');
Route::get('/districts', 'DataController@districts');
Route::get('/agas', 'DataController@agas');
Route::get('/postal', 'DataController@postals');

Route::get('/getlist', 'VillageController@getlist');

Route::get('/language/{locale}', function ($locale) {
	Session::set('applocale', $locale);
	App::setLocale($locale);
	return Redirect::back();
});



Route::resource('/village','VillageController');
Route::resource('/location','LocationController');
Route::resource('/person','PersonController');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::get('auth/facebook', 'Auth\AuthController@redirectToProvider');
Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallback');

//Route::get('excel', 'ExcelController@excel');

app/Models/Location.php
<?php

namespace App\Models;

use Moloquent;

class Location extends Moloquent
{
    //
    protected $connection = 'mongodb';
    protected $collection = 'location';
    protected $primaryKey = "_id";
    protected $fillable = [
    	'name','description','village_id', 'latlng'
    ];

    public function village()
    {
        return $this->belongsTo('App\Models\Village', 'village_id');
    }
    public function images()
    {
        return $this->embedsMany('App\Models\Locationimage');
    }

   

}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Location;
use App;
//use Request;
use Input;
use Image;

class LocationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $locations = Location::all();  
        return view('dashboard/location/index', ['locations'=>$locations]);        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $village_id = $request->input('village_id'); 
        $village = App\Models\Village::findOrFail($village_id);
        $data = ['village_id'=>$village_id, 'village'=>$village];
        return view('dashboard/location/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
        $loc = Location::create($input);
        if(Input::file()){
            $this->upload($loc->_id, $request);
        }
        
        return redirect('village/'.$input['village_id']);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $location = Location::findOrFail($id);  

        //return $village;
        return view('dashboard/location/show',['location'=>$location, 'images'=>$location->images()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $location = Location::findOrFail($id);
        return view('dashboard/location/edit',['location'=>$location]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $location = Location::findOrFail($id); 
        $location->update($request->all()) ;
       return redirect('location/'.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $location = Location::findOrFail($id);
        $img = $location->images()->all();
        foreach ($img as $i) {
            unlink(public_path('img/location/'.$i->name));
        }
        $location->delete(); 
        //$village = App\Models\Village::find($location->village_id);
        return redirect('village/'.$location->village_id);
    }
    public function destroyImge($lid, $id)
    {
        $location = Location::findOrFail($lid);
        $img = $location->images()->find($id);
        unlink(public_path('img/location/'.$img->name));
        $img->delete();
        //$village->images()->delete($id);
        //unlink(public_path('img/village/'.$img->name));
        return redirect('location/'.$lid);
    }
    public function upload($id, Request $request){

        $image = Input::file('file');
        $filename  = time() . '.' . $image->getClientOriginalExtension();
        $filename  = time() . '.' . $id.'.jpg';
        $path = public_path('img/location/'.$filename);
        Image::make($image->getRealPath())->resize(600, null, function ($constraint) {
            $constraint->aspectRatio();
        })->save($path);
        $location = Location::findOrFail($id);
        $image = $location->images()->create(array('name' => $filename));
        return redirect('location/'.$id);
        
    }


}

resources/views/dashboard/location/create.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6">    
        {!! Form::open(['url'=>'location' ,'files' => true]) !!}
        <h3>{{ trans('village.title_special_loc') }}</h3> 
        <div class="form-group">
            <input type="hidden" class="form-control" id="name" name="village_id" value="{{ $village_id }}">
            <label for="name">{{ trans('village.locationname') }}</label> 
            {!! Form::text('name', null, ['class'=>'form-control']) !!}            
        </div>       
        <div class="form-group">
            <label for="description">{{ trans('village.description') }}</label>
            {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
        </div>
        <div class="form-group">                     
            {!! Form::file('file') !!}            
        </div> 
        <div class="form-group">
            <label for="name">{{ trans('village.latlng') }}</label>
            <input type="text" class="form-control latlng" id="latlng" name="latlng" readonly="readonly">            
        </div> 
        <button type="submit" class="btn btn-primary">Submit</button>
        {!! Form::close() !!}    
    <br>
    <br>
    <br>
</div>
@stop


@section('script')
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=true"></script>
<script>
$(document).ready(function(){
    $('.latlng').on('click', function(e){
        $('.lightbox').show();
        $('.light-content').show();
        var province = "{{$village->province->name}}";        
        var district = "{{$village->district->name}}";
        var agadiv = "{{$village->agadiv->name}}";
        
        if (province === 'Please select') {
             province = '';
        };
        if (district === 'Please select') {
             district = '';
        };
        if (agadiv === 'Please select') {
             agadiv = '';
        };
        var txt ='';
       
        
        if (agadiv != '') {
            txt += agadiv+', '
        };
        if (district != '' ) {
            txt += district+' District, '
        };
         if (province != '') {
            txt += province+' Province, '
        };
        txt += 'Sri Lanka'
        console.log(txt );
        initMap(txt);
    });   
    $('.lightbox').on('click', function(e){
        $('.lightbox').hide();
        $('.light-content').hide();
        
    });


    function initMap(txt) {
      // Create a map object and specify the DOM element for display.
        var map;
        var markers = [];
        var latlng = $('#latlng').val();
        if (latlng !='') {
                latlng = latlng.split(',');
        }
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({
        'address': txt
        }, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
           
            if ($('#latlng').val() !='') {                
                var myOptions = {
                zoom: 10,
                center: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])},
                mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }else{
                var myOptions = {
                    zoom: 10,
                    center: results[0].geometry.location,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }
                
            map = new google.maps.Map(document.getElementById("map"), myOptions);
            
            var marker = new google.maps.Marker({
                position: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])}, 
                map: map
            });
            markers.push(marker);

            google.maps.event.addListener(map, "click", function(e) {  

                placeMarker(e.latLng);
                $('#latlng').val(e.latLng.lat()+','+e.latLng.lng());
                //console.log("Latitude: " + e.latLng.lat() + " Longitude: " + e.latLng.lng());
            });
            /*var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });*/
        }
        });
        
        function placeMarker(location) {
            clearMarkers();
            var marker = new google.maps.Marker({
                position: location, 
                map: map
            });
            markers.push(marker);
        }
        function clearMarkers() {
          for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
          }
        }

    }
});
</script>  
  
@stop

resources/views/dashboard/location/edit.blade.php
@extends('public/master')

@section('content')
<div class="col-md-6">    
        {!! Form::model($location, ['method'=>'PATCH', 'url'=>'location/'.$location->_id]) !!}
        <h3>{{ trans('village.title_special_loc') }}</h3> 
        <div class="form-group">
            <input type="hidden" class="form-control" id="name" name="location_id" value="{{ $location }}">
            <label for="name">{{ trans('village.locationname') }}</label> 
            {!! Form::text('name', null, ['class'=>'form-control']) !!}            
        </div>       
        <div class="form-group">
            <label for="description">{{ trans('village.description') }}</label>
            {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
        </div>         
        <div class="form-group">
            <label for="name">{{ trans('village.latlng') }}</label>
            {!! Form::text('latlng', null, ['readonly'=>'readonly' ,'class'=>'form-control latlng', 'id'=>'latlng']) !!}            
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        {!! Form::close() !!}    
    <br>
    <br>
    <br>
</div>
@stop


@section('script')
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=true"></script>
<script>
$(document).ready(function(){
    $('.latlng').on('click', function(e){
        $('.lightbox').show();
        $('.light-content').show();
        
        var province = "{{$location->village->province->name}}";        
        var district = "{{$location->village->district->name}}";
        var agadiv = "{{$location->village->agadiv->name}}";
        
        if (province === 'Please select') {
             province = '';
        };
        if (district === 'Please select') {
             district = '';
        };
        if (agadiv === 'Please select') {
             agadiv = '';
        };
        var txt ='';
       
        
        if (agadiv != '') {
            txt += agadiv+', '
        };
        if (district != '' ) {
            txt += district+' District, '
        };
         if (province != '') {
            txt += province+' Province, '
        };
        txt += 'Sri Lanka'
        console.log(txt );
        initMap(txt);
    });   
    $('.lightbox').on('click', function(e){
        $('.lightbox').hide();
        $('.light-content').hide();
        
    });


    function initMap(txt) {
      // Create a map object and specify the DOM element for display.
        var map;
        var markers = [];
        var latlng = $('#latlng').val();
        if (latlng !='') {
                latlng = latlng.split(',');
        }
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({
        'address': txt
        }, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
           
            if ($('#latlng').val() !='') {                
                var myOptions = {
                zoom: 10,
                center: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])},
                mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }else{
                var myOptions = {
                    zoom: 10,
                    center: results[0].geometry.location,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
            }
                
            map = new google.maps.Map(document.getElementById("map"), myOptions);
            
            var marker = new google.maps.Marker({
                position: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])}, 
                map: map
            });
            markers.push(marker);

            google.maps.event.addListener(map, "click", function(e) {  

                placeMarker(e.latLng);
                $('#latlng').val(e.latLng.lat()+','+e.latLng.lng());
                //console.log("Latitude: " + e.latLng.lat() + " Longitude: " + e.latLng.lng());
            });
            /*var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });*/
        }
        });
        
        function placeMarker(location) {
            clearMarkers();
            var marker = new google.maps.Marker({
                position: location, 
                map: map
            });
            markers.push(marker);
        }
        function clearMarkers() {
          for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
          }
        }

    }
});
</script>  
  
@stop

resources/views/dashboard/location/index.blade.php
@extends('public/master')

@section('content')
<div class="col-md-12">
	<h1>Locations</h1><!-- <a href="location/create"><span class="glyphicon glyphicon-plus"></span> Add new</a> -->
     <ul class="item_wrapper row">
    	 @foreach ($locations as $location)                         
	    <li class="col-md-2"><a href="/location/{{ $location->_id }}">{{translate($location, 'name')}}</a></li>
		@endforeach        	
    </ul>
</div>
@stop

resources/views/dashboard/location/show.blade.php
@extends('public/master')
@section('content')
<div class="col-md-6">
	<a href="/village/{{$location->village->id}}"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"> </span> {{translate($location->village, 'name')}}</a> 
	<h1>{{translate($location, 'name')}} <a href="/location/{{ $location->id }}/edit"><span class="badge">edit</span></a></h1>   
	<p>{{translate($location, 'description')}}</p>
</div>
<div class="col-md-6">
	<div class="row">
		<div class="col-md-12 mapouter"> 
			<div class="map mapbox" id="mapbox" ></div>			
		</div>

		<div class="col-md-12"> 
			<h3>Images</h3>	
			<div class="image_wrapper">

			@foreach ($location->images as $image)    
			<div class="imgthumb">                     
			    <a class="delimg" href="/location/deteleimage/{{{$location->id}}}/{{$image->id}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>                    
			    <img src="{{ URL::asset('img/location/'.$image->name) }}" alt="">
			</div>
			@endforeach
				<div class="clear"></div>
			</div> 
			{!! Form::open(['url'=>'location/upload/'.$location->_id ,'files' => true]) !!}       
		        <div class="form-group">   
		        	<input type="hidden" class="form-control" id="name" name="location_id" value="{{ $location->id }}">         
		            {!! Form::file('file') !!}            
		        </div>        
		        <button type="submit" class="btn btn-primary">Upload</button>
		    {!! Form::close() !!}
		</div>
	</div>
</div>
		
<div class="col-md-12">
<hr>
<form action="{{ URL::route('location.destroy',$location->id) }}" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <button>Delete Location</button>
</form>
</div>
@stop

@section('script')
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=true"></script>
<script>
$(document).ready(function(){
    
	initMap();

    function initMap() {
      // Create a map object and specify the DOM element for display.
        var map;
        
        var latlng ="{{ $location->latlng }}";
        if (latlng !='') {
                latlng = latlng.split(',');
        }
             
        var myOptions = {
        	zoom: 14,
	        center: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])},
	        mapTypeId: google.maps.MapTypeId.ROADMAP
	        }
                
        	map = new google.maps.Map(document.getElementById("mapbox"), myOptions);
        
	        var marker = new google.maps.Marker({
	            position: {lat: parseFloat(latlng[0]), lng: parseFloat(latlng[1])}, 
	            map: map
	        });
            
        }
        });
        

</script>  
  
@stop